# NAMESPACE: miwordpress
kind:           Namespace
apiVersion:     v1

metadata:
    name:       produccion
---
kind:           ConfigMap
apiVersion:     v1

metadata:
    name:       configuracion

data:
    clave1: Valor Produccion
    nombre: Ivan Produccion
---
kind:           Secret
apiVersion:     v1

metadata:
    name:       secretos

data:
    password:   cHJvZHVjY2lvbg== #base64 cHJvZHVjY2lvbg==
---
kind:           ConfigMap
apiVersion:     v1

metadata:
    name:       ficheros

data:
    conf.properties: |
        # Esto es el contenido de un fichero de configuracion
        # Este es uin comentario en el fichero
        
        # Aqui va la propieda mas importante del mundo mundial
        PROP=PRODUCCION
        
        # AQUI VA OTRA PROPIEDAD MENOS IMPORTANTE
        propiedad.memos.importante=No valgo na'
