# NAMESPACE: miwordpress
kind:           Namespace
apiVersion:     v1

metadata:
    name:       miwordpress-desarrollo
---
kind:           ConfigMap
apiVersion:     v1

metadata:
    name:       configuracion

data:
    clave1: Valor Desarrollo
    nombre: Ivan Desarrollo
---
kind:           Secret
apiVersion:     v1

metadata:
    name:       secretos

data:
    password:   ZGVzYXJyb2xsbw==
---
kind:           ConfigMap
apiVersion:     v1

metadata:
    name:       ficheros

data:
    conf.properties: |
        # Esto es el contenido de un fichero de configuracion
        # Este es uin comentario en el fichero
        
        # Aqui va la propieda mas importante del mundo mundial
        PROP=DESARROLLO
        
        # AQUI VA OTRA PROPIEDAD MENOS IMPORTANTE
        propiedad.memos.importante=No valgo na'